yolos_detector:
  ros__parameters:
    model_path: "" # overritten by the launch file (instead of using absolute path)
    labels_path: "" # overritten by the launch file
    conf_threshold: 0.4
    nms_threshold: 0.45
    publish_debug_image: false
    publish_timing: false
    ## the Topics to subscribe and publish are not params 
    ## so can only be remapped in the launch file
