/**
 * @file v_pace_db.h
 *
 * @brief This header file was generated by cantools version 42.0.1 Sat Aug  1 00:51:09 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef V_PACE_DB_H
#define V_PACE_DB_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define V_PACE_DB_VELOCITY_COMMAND_FRAME_ID (0x100u)
#define V_PACE_DB_VELOCITY_FEEDBACK_FRAME_ID (0x110u)
#define V_PACE_DB_STEERING_COMMAND_FRAME_ID (0x120u)
#define V_PACE_DB_STEERING_FEEDBACK_FRAME_ID (0x130u)
#define V_PACE_DB_RESET_COMMAND_FRAME_ID (0x140u)
#define V_PACE_DB_IMU_ACCEL_FRAME_ID (0x150u)
#define V_PACE_DB_IMU_GYRO_FLAGS_FRAME_ID (0x160u)

/* Frame lengths in bytes. */
#define V_PACE_DB_VELOCITY_COMMAND_LENGTH (8u)
#define V_PACE_DB_VELOCITY_FEEDBACK_LENGTH (8u)
#define V_PACE_DB_STEERING_COMMAND_LENGTH (8u)
#define V_PACE_DB_STEERING_FEEDBACK_LENGTH (8u)
#define V_PACE_DB_RESET_COMMAND_LENGTH (1u)
#define V_PACE_DB_IMU_ACCEL_LENGTH (8u)
#define V_PACE_DB_IMU_GYRO_FLAGS_LENGTH (8u)

/* Extended or standard frame types. */
#define V_PACE_DB_VELOCITY_COMMAND_IS_EXTENDED (0)
#define V_PACE_DB_VELOCITY_FEEDBACK_IS_EXTENDED (0)
#define V_PACE_DB_STEERING_COMMAND_IS_EXTENDED (0)
#define V_PACE_DB_STEERING_FEEDBACK_IS_EXTENDED (0)
#define V_PACE_DB_RESET_COMMAND_IS_EXTENDED (0)
#define V_PACE_DB_IMU_ACCEL_IS_EXTENDED (0)
#define V_PACE_DB_IMU_GYRO_FLAGS_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define V_PACE_DB_STEERING_FEEDBACK_AT_TARGET_FALSE_CHOICE (0u)
#define V_PACE_DB_STEERING_FEEDBACK_AT_TARGET_TRUE_CHOICE (1u)

#define V_PACE_DB_STEERING_FEEDBACK_POT_FAULT_FALSE_CHOICE (0u)
#define V_PACE_DB_STEERING_FEEDBACK_POT_FAULT_TRUE_CHOICE (1u)

#define V_PACE_DB_STEERING_FEEDBACK_OUT_OF_RANGE_FALSE_CHOICE (0u)
#define V_PACE_DB_STEERING_FEEDBACK_OUT_OF_RANGE_TRUE_CHOICE (1u)

#define V_PACE_DB_STEERING_FEEDBACK_SATURATED_FALSE_CHOICE (0u)
#define V_PACE_DB_STEERING_FEEDBACK_SATURATED_TRUE_CHOICE (1u)

#define V_PACE_DB_RESET_COMMAND_RESET_OFF_CHOICE (0u)
#define V_PACE_DB_RESET_COMMAND_RESET_ON_CHOICE (1u)

#define V_PACE_DB_IMU_GYRO_FLAGS_IMU_RESET_OFF_CHOICE (0u)
#define V_PACE_DB_IMU_GYRO_FLAGS_IMU_RESET_ON_CHOICE (1u)

/* Frame Names. */
#define V_PACE_DB_VELOCITY_COMMAND_NAME "VelocityCommand"
#define V_PACE_DB_VELOCITY_FEEDBACK_NAME "VelocityFeedback"
#define V_PACE_DB_STEERING_COMMAND_NAME "SteeringCommand"
#define V_PACE_DB_STEERING_FEEDBACK_NAME "SteeringFeedback"
#define V_PACE_DB_RESET_COMMAND_NAME "ResetCommand"
#define V_PACE_DB_IMU_ACCEL_NAME "ImuAccel"
#define V_PACE_DB_IMU_GYRO_FLAGS_NAME "ImuGyroFlags"

/* Signal Names. */
#define V_PACE_DB_VELOCITY_COMMAND_LEFT_VEL_SETPOINT_NAME "leftVelSetpoint"
#define V_PACE_DB_VELOCITY_COMMAND_RIGHT_VEL_SETPOINT_NAME "rightVelSetpoint"
#define V_PACE_DB_VELOCITY_FEEDBACK_LEFT_TICKS_NAME "leftTicks"
#define V_PACE_DB_VELOCITY_FEEDBACK_RIGHT_TICKS_NAME "rightTicks"
#define V_PACE_DB_STEERING_COMMAND_STEERING_SETPOINT_NAME "steeringSetpoint"
#define V_PACE_DB_STEERING_FEEDBACK_STEERING_ANGLE_NAME "steeringAngle"
#define V_PACE_DB_STEERING_FEEDBACK_AT_TARGET_NAME "at_target"
#define V_PACE_DB_STEERING_FEEDBACK_POT_FAULT_NAME "pot_fault"
#define V_PACE_DB_STEERING_FEEDBACK_OUT_OF_RANGE_NAME "out_of_range"
#define V_PACE_DB_STEERING_FEEDBACK_SATURATED_NAME "saturated"
#define V_PACE_DB_RESET_COMMAND_RESET_NAME "reset"
#define V_PACE_DB_IMU_ACCEL_ACCEL_X_NAME "accel_x"
#define V_PACE_DB_IMU_ACCEL_ACCEL_Y_NAME "accel_y"
#define V_PACE_DB_IMU_ACCEL_ACCEL_Z_NAME "accel_z"
#define V_PACE_DB_IMU_ACCEL_SEQUENCE_NAME "sequence"
#define V_PACE_DB_IMU_ACCEL_RESERVED_NAME "reserved"
#define V_PACE_DB_IMU_GYRO_FLAGS_GYRO_X_NAME "gyro_x"
#define V_PACE_DB_IMU_GYRO_FLAGS_GYRO_Y_NAME "gyro_y"
#define V_PACE_DB_IMU_GYRO_FLAGS_GYRO_Z_NAME "gyro_z"
#define V_PACE_DB_IMU_GYRO_FLAGS_IMU_RESET_NAME "imu_reset"
#define V_PACE_DB_IMU_GYRO_FLAGS_SEQUENCE_NAME "sequence"

/**
 * Signals in message VelocityCommand.
 *
 * Per-wheel velocity setpoints (Ackermann: 2 independent rear drives)
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_velocity_command_t {
    /**
     * Left rear wheel velocity setpoint
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float left_vel_setpoint;

    /**
     * Right rear wheel velocity setpoint
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float right_vel_setpoint;
};

/**
 * Signals in message VelocityFeedback.
 *
 * Cumulative signed encoder ticks per wheel (odometry source)
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_velocity_feedback_t {
    /**
     * Left wheel cumulative signed encoder ticks
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t left_ticks;

    /**
     * Right wheel cumulative signed encoder ticks
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t right_ticks;
};

/**
 * Signals in message SteeringCommand.
 *
 * Steering angle setpoint (separate frame from velocity, per contract)
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_steering_command_t {
    /**
     * Steering angle setpoint (+left, REP-103)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float steering_setpoint;
};

/**
 * Signals in message SteeringFeedback.
 *
 * Measured steering angle + status bitfield. Broadcast: consumed by BOTH JETSON and CLUSTER - the cluster reuses this frame rather than duplicating the angle into a cluster-specific frame.
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_steering_feedback_t {
    /**
     * Measured steering angle from pot (+left, REP-103). Consumed by JETSON and rendered by CLUSTER.
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float steering_angle;

    /**
     * b0 AT_TARGET: the CLAMPED setpoint was reached. Because it refers to the clamped value, AT_TARGET together with OUT_OF_RANGE means the request exceeded travel, was clamped, and that limit was reached - so read AT_TARGET ONLY alongside OUT_OF_RANGE.
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t at_target;

    /**
     * b1 POT_FAULT: steering pot reading implausible. CLUSTER should grey out the steering display when set.
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t pot_fault;

    /**
     * b2 OUT_OF_RANGE: the requested angle exceeded the mechanical travel and was clamped.
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t out_of_range;

    /**
     * b3 SATURATED: the servo command hit its pulse-width limit.
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t saturated;
};

/**
 * Signals in message ResetCommand.
 *
 * Odometry reset: Tiva zeroes its encoder tick counters on receipt (Jetson sends once on activate; it does not self-zero)
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_reset_command_t {
    /**
     * 1 = zero the encoder tick counters now. Only bit 0 is meaningful; the whole byte is reserved so the Jetson's existing 1-byte payload maps directly. Fire-and-forget: no acknowledgement frame is sent or expected.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reset;
};

/**
 * Signals in message ImuAccel.
 *
 * IMU accelerometer X/Y/Z with sequence counter. 1 LSB = 0.001 m/s^2.
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_imu_accel_t {
    /**
     * Accelerometer X (bytes 0-1)
     *
     * Range: -32768..32767 (-32.768..32.767 m/s^2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_x;

    /**
     * Accelerometer Y (bytes 2-3)
     *
     * Range: -32768..32767 (-32.768..32.767 m/s^2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_y;

    /**
     * Accelerometer Z (bytes 4-5)
     *
     * Range: -32768..32767 (-32.768..32.767 m/s^2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_z;

    /**
     * Sample-cycle counter (byte 6). MUST equal ImuGyroFlags.sequence for the same sample - the Jetson rejects the whole read when they differ.
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t sequence;

    /**
     * Reserved (byte 7), send 0
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reserved;
};

/**
 * Signals in message ImuGyroFlags.
 *
 * IMU gyroscope X/Y/Z, IMU reset flag and sequence counter. 1 LSB = 0.001 rad/s.
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_imu_gyro_flags_t {
    /**
     * Gyroscope X (bytes 0-1)
     *
     * Range: -32768..32767 (-32.768..32.767 rad/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_x;

    /**
     * Gyroscope Y (bytes 2-3)
     *
     * Range: -32768..32767 (-32.768..32.767 rad/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_y;

    /**
     * Gyroscope Z (bytes 4-5). The TIVA pre-inverts this to the robot frame; the Jetson applies no host-side inversion.
     *
     * Range: -32768..32767 (-32.768..32.767 rad/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_z;

    /**
     * 1 = the IMU was re-initialised/crashed and recovered (byte 6). The Jetson forces gyro Z to 0 and holds its existing calibration while this is set.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t imu_reset;

    /**
     * Sample-cycle counter (byte 7 - NOT byte 6 as in ImuAccel). MUST equal ImuAccel.sequence for the same sample.
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t sequence;
};

/**
 * Pack message VelocityCommand.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int v_pace_db_velocity_command_pack(
    uint8_t *dst_p,
    const struct v_pace_db_velocity_command_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VelocityCommand.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_velocity_command_init(struct v_pace_db_velocity_command_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float v_pace_db_velocity_command_left_vel_setpoint_encode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_velocity_command_left_vel_setpoint_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_velocity_command_left_vel_setpoint_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float v_pace_db_velocity_command_right_vel_setpoint_encode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_velocity_command_right_vel_setpoint_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_velocity_command_right_vel_setpoint_is_in_phys_range(float value);

/**
 * Unpack message VelocityFeedback.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int v_pace_db_velocity_feedback_unpack(
    struct v_pace_db_velocity_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VelocityFeedback.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_velocity_feedback_init(struct v_pace_db_velocity_feedback_t *msg_p);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_velocity_feedback_left_ticks_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_velocity_feedback_left_ticks_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_velocity_feedback_left_ticks_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_velocity_feedback_right_ticks_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_velocity_feedback_right_ticks_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_velocity_feedback_right_ticks_is_in_phys_range(float value);

/**
 * Pack message SteeringCommand.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int v_pace_db_steering_command_pack(
    uint8_t *dst_p,
    const struct v_pace_db_steering_command_t *src_p,
    size_t size);

/**
 * Init message fields to default values from SteeringCommand.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_steering_command_init(struct v_pace_db_steering_command_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float v_pace_db_steering_command_steering_setpoint_encode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_command_steering_setpoint_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_command_steering_setpoint_is_in_phys_range(float value);

/**
 * Unpack message SteeringFeedback.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int v_pace_db_steering_feedback_unpack(
    struct v_pace_db_steering_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from SteeringFeedback.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_steering_feedback_init(struct v_pace_db_steering_feedback_t *msg_p);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_steering_feedback_steering_angle_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_feedback_steering_angle_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_feedback_steering_angle_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_steering_feedback_at_target_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_feedback_at_target_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_feedback_at_target_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_steering_feedback_pot_fault_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_feedback_pot_fault_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_feedback_pot_fault_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_steering_feedback_out_of_range_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_feedback_out_of_range_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_feedback_out_of_range_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_steering_feedback_saturated_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_feedback_saturated_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_feedback_saturated_is_in_phys_range(float value);

/**
 * Pack message ResetCommand.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int v_pace_db_reset_command_pack(
    uint8_t *dst_p,
    const struct v_pace_db_reset_command_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ResetCommand.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_reset_command_init(struct v_pace_db_reset_command_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t v_pace_db_reset_command_reset_encode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_reset_command_reset_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_reset_command_reset_is_in_phys_range(float value);

/**
 * Unpack message ImuAccel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int v_pace_db_imu_accel_unpack(
    struct v_pace_db_imu_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ImuAccel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_imu_accel_init(struct v_pace_db_imu_accel_t *msg_p);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_accel_accel_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_x_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_x_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_accel_accel_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_y_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_y_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_accel_accel_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_z_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_z_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_accel_sequence_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_sequence_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_sequence_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_accel_reserved_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_reserved_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_reserved_is_in_phys_range(float value);

/**
 * Unpack message ImuGyroFlags.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int v_pace_db_imu_gyro_flags_unpack(
    struct v_pace_db_imu_gyro_flags_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ImuGyroFlags.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_imu_gyro_flags_init(struct v_pace_db_imu_gyro_flags_t *msg_p);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_gyro_flags_gyro_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_x_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_x_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_gyro_flags_gyro_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_y_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_y_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_gyro_flags_gyro_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_z_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_z_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_gyro_flags_imu_reset_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_imu_reset_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_imu_reset_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_gyro_flags_sequence_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_sequence_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_sequence_is_in_phys_range(float value);


#ifdef __cplusplus
}
#endif

#endif
